name:                RFC5646
version:             0.1.0.0
github:              https://github.com/naoto-ogawa/RFC5646
license:             MIT 
author:              Naoto Ogawa
maintainer:          becausethespiderspiedher@gmail.com 
copyright:           2018 Naoto Ogawa

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/naoto-ogawa/RFC5646#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - attoparsec
    - base
    - bytestring
    - lens
    - mtl
  exposed-modules:
    - RFC.RFC5646
#    - RFC.Internal.RFC5646

tests:
  RFC5646-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - RFC5646
    - tasty
    - tasty-discover
    - tasty-hunit
    - tasty-hspec
    - tasty-quickcheck 
    - tasty-smallcheck 
    - lens
    - mtl
    - attoparsec
    - bytestring
  RFC5646-doctest:
    main: test/doctests.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - RFC5646 
    - doctest
